# Generated by Django 5.2 on 2025-10-04 16:49

import django.utils.timezone
import socialsched.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_on', models.DateTimeField()),
                ('post_timezone', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('account_id', models.IntegerField()),
                ('description', models.TextField(max_length=63206)),
                ('media_file', models.FileField(blank=True, max_length=100000, null=True, upload_to=socialsched.models.get_filename)),
                ('media_file_type', models.CharField(blank=True, choices=[('VIDEO', 'video'), ('IMAGE', 'image')], max_length=50, null=True)),
                ('process_image', models.BooleanField(blank=True, default=True, null=True)),
                ('process_video', models.BooleanField(blank=True, default=True, null=True)),
                ('image_processed', models.BooleanField(blank=True, default=False, null=True)),
                ('video_processed', models.BooleanField(blank=True, default=False, null=True)),
                ('post_on_x', models.BooleanField(blank=True, default=False, null=True)),
                ('post_on_instagram', models.BooleanField(blank=True, default=False, null=True)),
                ('post_on_facebook', models.BooleanField(blank=True, default=False, null=True)),
                ('post_on_linkedin', models.BooleanField(blank=True, default=False, null=True)),
                ('post_on_tiktok', models.BooleanField(blank=True, default=False, null=True)),
                ('link_x', models.CharField(blank=True, max_length=50000, null=True)),
                ('link_instagram', models.CharField(blank=True, max_length=50000, null=True)),
                ('link_facebook', models.CharField(blank=True, max_length=50000, null=True)),
                ('link_linkedin', models.CharField(blank=True, max_length=50000, null=True)),
                ('link_tiktok', models.CharField(blank=True, max_length=50000, null=True)),
                ('error_x', models.CharField(blank=True, max_length=50000, null=True)),
                ('error_instagram', models.CharField(blank=True, max_length=50000, null=True)),
                ('error_facebook', models.CharField(blank=True, max_length=50000, null=True)),
                ('error_linkedin', models.CharField(blank=True, max_length=50000, null=True)),
                ('error_tiktok', models.CharField(blank=True, max_length=50000, null=True)),
                ('retries_x', models.IntegerField(blank=True, default=0, null=True)),
                ('retries_instagram', models.IntegerField(blank=True, default=0, null=True)),
                ('retries_facebook', models.IntegerField(blank=True, default=0, null=True)),
                ('retries_linkedin', models.IntegerField(blank=True, default=0, null=True)),
                ('retries_tiktok', models.IntegerField(blank=True, default=0, null=True)),
                ('tiktok_nickname', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('tiktok_max_video_post_duration_sec', models.IntegerField(blank=True, default=None, null=True)),
                ('tiktok_privacy_level_options', models.CharField(blank=True, choices=[('FOLLOWER_OF_CREATOR', 'Followers of Creator'), ('PUBLIC_TO_EVERYONE', 'Public to Everyone'), ('MUTUAL_FOLLOW_FRIENDS', 'Mutual Follow Friends'), ('SELF_ONLY', 'Self Only')], default=None, max_length=1000, null=True)),
                ('tiktok_allow_comment', models.BooleanField(blank=True, default=None, null=True)),
                ('tiktok_allow_duet', models.BooleanField(blank=True, default=None, null=True)),
                ('tiktok_allow_stitch', models.BooleanField(blank=True, default=None, null=True)),
                ('tiktok_disclose_video_content', models.BooleanField(blank=True, default=None, null=True)),
                ('tiktok_your_brand', models.BooleanField(blank=True, default=None, null=True)),
                ('tiktok_branded_content', models.BooleanField(blank=True, default=None, null=True)),
                ('tiktok_ai_generated', models.BooleanField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'scheduled',
            },
        ),
    ]
