# Generated by Django 5.2 on 2025-10-04 16:49

import integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('user_id', models.CharField(blank=True, max_length=5000, null=True)),
                ('access_token', models.CharField(blank=True, max_length=5000, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=5000, null=True)),
                ('access_expire', models.DateTimeField(blank=True, null=True)),
                ('refresh_expire', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('X', 'X'), ('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok')], max_length=1000)),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=100000, null=True)),
                ('avatar', models.ImageField(blank=True, max_length=100000, null=True, upload_to=integrations.models.get_filename)),
            ],
            options={
                'verbose_name_plural': 'integrations',
            },
        ),
    ]
